pipeline {
    agent any

    environment {
        COMPOSE_PROJECT_NAME = "oidc-app"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'feature/cicd-docker-pipeline',
                    url: 'https://github.com/hiimwin/MyOdicServerDemo.git',
                    credentialsId: 'github-token'
            }
        }

        stage('Stop Old Containers') {
            steps {
                sh '''
                echo "Stop old containers"
                docker-compose down -v || true
                '''
            }
        }

        stage('Build & Run with Docker Compose') {
            steps {
                sh '''
                echo "Build & start containers"
                docker-compose up -d --build
                '''
            }
        }

        stage('Check Running Containers') {
            steps {
                sh '''
                echo "Running containers:"
                docker ps
                '''
            }
        }

        stage('Test Endpoint') {
            steps {
                sh '''
                echo "Testing client endpoint..."
                sleep 5
                curl -I http://localhost:5001 || exit 1
                '''
            }
        }
    }

    post {
        success {
            echo "CI/CD SUCCESS - App is running"
        }
        failure {
            echo "CI/CD FAILED"
        }
        always {
            sh 'docker ps'
        }
    }
}