version: "3.9"

services:
  oidc-server:
    image: oidc-server-${BRANCH_NAME_SAFE}
    networks:
      - branch_net
    environment:
      ASPNETCORE_URLS: http://+:80

  oidc-client:
    image: oidc-client-${BRANCH_NAME_SAFE}
    networks:
      - branch_net
    depends_on:
      - oidc-server

networks:
  branch_net:
    external: true